#! /bin/sh
set -eu

srcdir="$HOME/pkglint"
archivedir="$srcdir/archive"
pkgsrcdir="$HOME/git/pkgsrc"

genrunid() {
  if [ -n "${genrunid-}" ]; then
    return
  fi
  headcommit=$(cd "$srcdir" && git rev-parse --short HEAD)
  if (cd "$srcdir" && git diff --quiet && git diff --cached --quiet); then
    timestamp="$(cd "$srcdir" && git show -s --format=%ai HEAD | awk -F '[- :]' '{print $1$2$3"-"$4$5}')"
    runid="$timestamp-$headcommit"
  else
    runid="$(date +'%Y%m%d-%H%M')-$headcommit-mod-$$"
  fi
}

install() {
  genrunid
  echo "=> Installing pkglint"
  (cd "$srcdir" && chmod 644 *.go)
  (cd "$srcdir" && go fmt netbsd.org/pkglint/... && go test netbsd.org/pkglint/... && go install && cp "$GOPATH/bin/pkglint.exe" "$archivedir/$runid.exe")
}

install_notest() {
  genrunid
  echo "=> Installing pkglint"
  (cd "$srcdir" && chmod 644 *.go)
  (cd "$srcdir" && go fmt netbsd.org/pkglint/... && go install && cp "$GOPATH/bin/pkglint.exe" "$archivedir/$runid.exe")
}

analyze() {
  echo "=> Analyzing test coverage"
  (cd ~/pkglint && gocover)

  echo "=> Analyzing code style"
  (cd ~/pkglint && gometalinter --exclude "exported method|unexported|drop this else") | less
}

netbsd() {
  echo "=> Copying files to NetBSD VM"
  rsync -a --delete --rsync-path=/home/rillig/pkg/bin/rsync \
    --cvs-exclude \
    --exclude="qa-pkglint" \
    --exclude="**.[01]" \
    --exclude=".git*" \
    --exclude="/COPYING" \
    --exclude="/README.md" \
    --exclude="/archive/" \
    --exclude="/coverage.html" \
    --exclude="/pkglint.cov" \
    --exclude="/pkglint.exe" \
    --exclude="/pkglint.test.exe" \
    --exclude="*.docx" \
    --exclude="/.idea/" \
    --exclude="*.iml" \
    --exclude="*yacc.go" \
    --exclude="*.log" \
    ~/pkglint/ netbsd:proj/pkgsrc/pkgtools/pkglint/files/

  echo "=> Installing NetBSD package"
  ssh netbsd ". ./.bash_profile && cd proj/pkgsrc/pkgtools/pkglint && bmake clean update"
}

pkgsrc() {
  genrunid
  echo "=> Running pkglint on the pkgsrc tree"
  time (cd "$pkgsrcdir" && "$archivedir/$runid.exe" -pr -Wall -Call . wip) > "$archivedir/$runid.tmp" || true
  mv "$archivedir/$runid.tmp" "$archivedir/$runid.out"
}

diffs() {
  echo "=> Generating diffs"
  (
    cd "$archivedir"
    for out in *.out; do
      diff -u "reference" "$out" > "${out%.out}.diff" || true
      perl -e '
        use strict;
        use warnings;

        sub readhisto($) {
          my ($fname) = @_;
          my %histo = ();
          open(my $f, "<", $fname) or die;
          while (defined(my $line = <$f>)) {
            if ($line =~ /^loghisto\s+(\d+)\s+(.*)$/) {
              $histo{$2} = +$1;
            }
          }
          return \%histo;
        }

        my $del = readhisto(shift());
        my $add = readhisto(shift());
        my %all = ();
        foreach my $key (keys %$del) { $all{$key} += $del->{$key}; }
        foreach my $key (keys %$add) { $all{$key} += $add->{$key}; }
        foreach my $key (sort { $all{$b} <=> $all{$a} || $a cmp $b } keys %all) {
          my $ndel = exists($del->{$key}) ? $del->{$key} : 0;
          my $nadd = exists($add->{$key}) ? $add->{$key} : 0;
          if ($ndel != $nadd) {
            printf("%5d   %5d   %+5d   %s\n", $ndel, $nadd, $nadd - $ndel, $key);
          }
        }
        ' "reference" "$out" >> "${out%.out}.diff"
    done
  )
}

if [ $# -eq 0 ]; then
  set -- genrunid install pkgsrc diffs
fi
for cmd in "$@"; do
  "$cmd"
done
echo "=> OK"
